POST http://localhost:3000/api/users
Content-Type: application/json
Accept: application/json

{
  "email" : "user@example.com",
  "password" : "rahasia",
  "first_name" : "User",
  "last_name" : "Cashier",
  "address" : "Jalan 1",
  "birth_date" : "2000-02-20"
}

### 

POST http://localhost:3000/api/users/login
Content-Type: application/json
Accept: application/json

{
  "email" : "user@example.com",
  "password" : "rahasia"
}

###

DELETE http://localhost:3000/api/users/logout
Content-Type: application/json
Accept: application/json
Authorization: 6e474614-c0b1-46e8-bff5-f2b84b3589e1

###

GET http://localhost:3000/api/users/current
Content-Type: application/json
Accept: application/json
Authorization: 4aa41cdb-c4c6-4642-a0b0-f6183bb7d11f

###

PATCH http://localhost:3000/api/users/current
Content-Type: application/json
Accept: application/json
Authorization: 4aa41cdb-c4c6-4642-a0b0-f6183bb7d11f

{
  "image" : "image.img"
}